# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

version: "3.9"
services:
  web:
    build: .
    command: '/start-reload.sh'
    container_name: http_trigger_example
    environment:
      MORA_URL: https://morademo.magenta.dk

      SD_USERNAME: 'SYSYUSER01'
      SD_PASSWORD: 'password1'
      SD_INSTITUTION: 'ID'

#      JAEGER_HOSTNAME: "jaeger"
    ports:
      - "5011:80"
    volumes:
      - ./app:/app

#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "14268"
#      - "14250"
